version: "3.7"

services:
  php:
    build: .docker/php
    volumes:
      - ./volumes/akaunting:/var/www/html
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm/
    restart: unless-stopped
    environment:
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
      - AKAUNTING_VERSION
      - ADM_EMAIL
      - ADM_PASSWD

      - APP_ENV

      - DB_CONNECTION
      - DB_PORT
      - DB_HOST
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD

      - XDEBUG_CONFIG
    extra_hosts:
      - host.docker.internal:host-gateway
  web:
    build:
      context: .docker/nginx
      args:
        NGINX_CONF: http
    restart: unless-stopped
    volumes:
      - ./volumes/akaunting:/var/www/html:ro
    depends_on:
      - php
    ports:
      - 80:80
  mysql:
    image: mysql
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - ./volumes/mysql/dump:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-akaunting}