version: "3.7"

services:
  php:
    build: .docker/php
    volumes:
      - /storage/akaunting:/var/www/html
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm/
    restart: unless-stopped
    environment:
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
      - AKAUNTING_VERSION="3"
      - XDEBUG_CONFIG
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file: "stack.env"
  web:
    build:
      context: .docker/nginx
      args:
        NGINX_CONF: http
    restart: unless-stopped
    volumes:
      - /storage/akaunting:/var/www/html:ro
    depends_on:
      - php
    networks:
      - traefik-proxy
    labels:
    #UI
      - "traefik.enable=true"
      - "traefik.http.routers.comptapapa.entrypoints=web"
      - "traefik.http.middlewares.comptapapa-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.comptapapa.middlewares=comptapapa-https-redirect"
      - "traefik.http.routers.comptapapa-secure.entrypoints=websecure"
      - "traefik.http.routers.comptapapa-secure.rule=Host(`comptapapa.spearheadsounds.com`)"
      - "traefik.http.routers.comptapapa-secure.tls=true"
      - "traefik.http.routers.comptapapa-secure.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.comptapapa-secure.service=comptapapa-secure"
      - "traefik.http.services.comptapapa-secure.loadbalancer.server.port=80"
    env_file: "stack.env"
  mysql:
    image: mysql
    volumes:
      - /storage/aukaunting/mysql/data:/var/lib/mysql
      - ./volumes/mysql/dump:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-akaunting}
    env_file: "stack.env"

networks:
  traefik-proxy:
    external: true
