version: "3.7"

services:
  php:
    build: .docker/php7
    volumes:
      - ./volumes/akaunting:/akaunting
      - ~/.composer:/root/.composer
      - ~/.npm:/root/.npm/
    restart: unless-stopped
    environment:
      - AKAUNTING_VERSION
      - ADM_EMAIL
      - ADM_PASSWD

      - APP_ENV

      - DB_CONNECTION
      - DB_PORT
      - DB_HOST
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
  web:
    build:
      context: .docker/nginx
      args:
        NGINX_CONF: http
    restart: unless-stopped
    volumes:
      - ./volumes/akaunting:/akaunting:ro
      - ~/volumes/certs:/etc/nginx/certs
    depends_on:
      - php
    ports:
      - 80:80
  mariadb:
    image: mariadb
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - ./volumes/mysql/dump:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE