version: "3.7"

services:
  php:
    build: .docker/php7
    volumes:
      - ./volumes/akaunting:/akaunting
      - ~/.composer:/root/.composer
    env_file:
      - .env
    restart: unless-stopped

  web:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./volumes/akaunting:/akaunting:ro
      - ./.docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - ~/volumes/certs:/etc/nginx/certs
    depends_on:
      - php
    ports:
      - 80:80