version: "3.7"

services:
  php:
    build: .docker/php
    volumes:
      - ./volumes/akaunting:/akaunting
      - ~/.composer:/root/.composer
      - ~/.npm:/root/.npm/
    restart: unless-stopped
    environment:
      - AKAUNTING_VERSION
      - ADM_EMAIL
      - ADM_PASSWD

      - APP_ENV

      - DB_CONNECTION
      - DB_PORT
      - DB_HOST
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD

      - XDEBUG_CONFIG
  web:
    build:
      context: .docker/nginx
      args:
        NGINX_CONF: http
    restart: unless-stopped
    volumes:
      - ./volumes/akaunting:/akaunting:ro
    depends_on:
      - php
    ports:
      - 80:80
  mysql:
    image: mysql
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - ./volumes/mysql/dump:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE